# Exercice : analyse de données sur Thanksgiving

## Import des données

1ère étape habituelle : importer les librairies nécessaires, les données thanksgiving.csv et les afficher

In [1]:
import pandas as pd
data = pd.read_csv('Data/thanksgiving.csv', encoding='iso-8859-1')
# encoding = 'Latin-1'; encoding= 'ISO-8859-1'
data.head(10)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific
5,4337929779,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Urban,18 - 29,Male,"$0 to $9,999",Pacific
6,4337924420,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,Yes,Yes,No,Rural,18 - 29,Male,"$25,000 to $49,999",East North Central
7,4337916002,Yes,Turkey,NaN,Baked,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,Yes,Yes,Rural,18 - 29,Male,Prefer not to answer,Mountain
8,4337914977,Yes,Turkey,NaN,Roasted,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$75,000 to $99,999",Middle Atlantic
9,4337899817,Yes,Other (please specify),Turkey and Ham,Baked,NaN,Bread-based,NaN,Other (please specify),Both Canned and Homemade,...,No,No,No,Yes,Yes,Suburban,30 - 44,Male,"$25,000 to $49,999",East South Central

In [2]:
data.columns

Index(['RespondentID', 'Do you celebrate Thanksgiving?',
       'What is typically the main dish at your Thanksgiving dinner?',
       'What is typically the main dish at your Thanksgiving dinner? - Other (please specify)',
       'How is the main dish typically cooked?',
       'How is the main dish typically cooked? - Other (please specify)',
       'What kind of stuffing/dressing do you typically have?',
       'What kind of stuffing/dressing do you typically have? - Other (please specify)',
       'What type of cranberry saucedo you typically have?',
       'What type of cranberry saucedo you typically have? - Other (please specify)',
       'Do you typically have gravy?',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1',
       'Do you typically pray before or after the Thanksgiving meal?',
       'How far will you travel for Thanksgiving?',
       'Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade',
       'What's the age cutoff at your "kids' table" at Thanksgiving?',
       'Have you ever tried to meet up with hometown friends on Thanksgiving night?',
       'Have you ever attended a "Friendsgiving?"',
       'Will you shop any Black Friday sales on Thanksgiving Day?',
       'Do you work in retail?',
       'Will you employer make you work on Black Friday?',
       'How would you describe where you live?', 'Age', 'What is your gender?',
       'How much total combined money did all members of your HOUSEHOLD earn last year?',
       'US Region'],
      dtype='object')

## Filtrage des données

- Comptez le nombre de personne qui célèbrent Thanksgiving.  
- Conservez dans votre dataframe uniquement les individus qui célèbrent Thanksgiving.  
>Indications :
>- Il existe une méthode Series.value_counts()
>- La colonne 'Do you celebrate Thanksgiving?' devrait être utile
>- Pour rappel, on peut tout à fait réaffecter une partie d'un dataframe à la variable contenant ce dataframe

In [3]:
#méthode value_counts()
data['Do you celebrate Thanksgiving?'].value_counts()

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

In [4]:
#avec compteur
cpt = 0
for idx in range(data.shape[0]): #for idx in range(len(data.iloc[:,1]))
    if data.iloc[idx,1]=='Yes':
        cpt+=1

cpt2=0
for val in data['Do you celebrate Thanksgiving?']:
    if val == 'Yes':
        cpt2+=1
        
print(cpt, cpt2)

980 980

In [5]:
#avec un filtre
filtre = data['Do you celebrate Thanksgiving?']=='Yes'

filtre.sum()
data[filtre].shape[0]

980

In [2]:
filtre = data['Do you celebrate Thanksgiving?']=='Yes'
data = data[filtre]
data.shape

(980, 65)

## Exploration des données : les repas de Thanksgiving

- Utiliser la méthode Series.value_counts() pour afficher combien de fois chaque résultat apparaît pour la question 'What is typically the main dish at your Thanksgiving dinner?'.
- Afficher les colonnes 'What is typically the main dish at your Thanksgiving dinner?' et 'Do you typically have gravy?' pour les individus qui mangent du 'Tofurkey' (la dinde de tofu).

In [7]:
data['What is typically the main dish at your Thanksgiving dinner?'].value_counts()

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [4]:
filtre = data['What is typically the main dish at your Thanksgiving dinner?']=='Tofurkey'

#data[['What is typically the main dish at your Thanksgiving dinner?','Do you typically have gravy?']][filtre]

#data[filtre][['What is typically the main dish at your Thanksgiving dinner?','Do you typically have gravy?']]

data.loc[filtre,['What is typically the main dish at your Thanksgiving dinner?','Do you typically have gravy?']]

,What is typically the main dish at your Thanksgiving dinner?,Do you typically have gravy?
4,Tofurkey,Yes
33,Tofurkey,Yes
69,Tofurkey,No
72,Tofurkey,No
77,Tofurkey,Yes
145,Tofurkey,Yes
175,Tofurkey,Yes
218,Tofurkey,No
243,Tofurkey,Yes
275,Tofurkey,No
393,Tofurkey,Yes
399,Tofurkey,Yes
571,Tofurkey,Yes
594,Tofurkey,Yes
628,Tofurkey,No
774,Tofurkey,No
820,Tofurkey,No
837,Tofurkey,Yes
860,Tofurkey,No
953,Tofurkey,Yes

## Convertir l'âge en une valeur numérique

- Ecrire une fonction permettant de convertir les valeurs de la colonne 'Age' en valeur numérique, à savoir la moyenne entre l'âge inférieur et l'âge supérieur des tranches d'âges utilisées. Cette fonction prendra donc en paramètre une chaine de caractères (les valeurs actuelles de la colonne 'Age') et retournera la moyenne des deux âges de chaque tranche.
> Indications (si vous voulez vous pouvez faire sans bien sûr !) :
>- Faire en sorte que la fonction ne retourne rien (cf None) si les valeurs sont nulles
>- Remplacer le caractère '+' avec une chaine de caractères vide en remplacement pour le supprimer (méthode replace())
>- Séparer les chaines de caractères (méthode split()) pour en extraire les bornes d'age
>- utiliser int() pour convertir le résultat en entier
>- Retourner le résultat
- Utiliser la méthode Series.apply() pour appliquer la fonction à chaque valeur de la colonne 'Age' du dataframe data et créer une nouvelle variable age_num.
- Appeler la méthode Series.describe() sur la colonne 'age_num'.

In [9]:
def age(chaine):
    if pd.isnull(chaine):
        return None
    else:
        chaine = chaine.replace('+','')
        liste = chaine.split(' ')
        inf = int(liste[0])
        sup = int(liste[-1])
        return (inf+sup)/2

In [10]:
data['age_num']=data['Age'].apply(age)
data['age_num'].describe()

count    947.000000
mean      44.889652
std       13.475203
min       23.500000
25%       37.000000
50%       52.000000
75%       60.000000
max       60.000000
Name: age_num, dtype: float64

## Convertir les revenus en valeurs numériques

Appliquer exactement la même méthodologie pour convertir le revenu (colonne 'How much total combined money did all members of your HOUSEHOLD earn last year?') en valeur numérique.  
Nommer la nouvelle variable 'income_num'.

In [11]:
def rev(ch):
    if pd.isnull(ch) or ch[0]=='P':
        return None
    else:
        ch = ch.replace('$','')
        ch = ch.replace(',','')
        ch = ch.replace(' and up','')
        liste = ch.split(' ')
        inf = int(liste[0])
        sup = int(liste[-1])
        return (inf+sup)/2

In [12]:
data['income_num']=data['How much total combined money did all members of your HOUSEHOLD earn last year?'].apply(rev)
data['income_num'].describe()

count       829.000000
mean      86486.276840
std       57789.467567
min        4999.500000
25%       37499.500000
50%       87499.500000
75%      112499.500000
max      200000.000000
Name: income_num, dtype: float64

## Corrélation entre distance et revenus

- Regarder de quelle manière les personnes gagnant moins de 100000 dollars voyagent.
> _Indications :_ Utiliser les variables 'int_income' et 'How far will you travel for Thanksgiving?'
- Faire de même avec les personnes gagnant plus de 100000 dollars.

In [13]:
# avec filtre
filtre = data['income_num']<100000
#data[filtre]['How far will you travel for Thanksgiving?'].value_counts()
#data[~filtre]['How far will you travel for Thanksgiving?'].value_counts()
data[~filtre].pivot_table(index = 'How far will you travel for Thanksgiving?',
                         values = 'income_num', aggfunc = 'count')

                                                    income_num
How far will you travel for Thanksgiving?
Thanksgiving is happening at my home--I won't t...         142
Thanksgiving is local--it will take place in th...          74
Thanksgiving is out of town and far away--I hav...          32
Thanksgiving is out of town but not too far--it...          49

In [17]:
# avec une nouvelle variable
data['inc100'] = data['income_num']<100000
data.pivot_table(index = 'How far will you travel for Thanksgiving?',
                 columns = 'inc100',
                 values = 'income_num',
                 aggfunc = 'count',
                 margins = True)

inc100                                              False  True  All
How far will you travel for Thanksgiving?
Thanksgiving is happening at my home--I won't t...    142   205  347
Thanksgiving is local--it will take place in th...     74   163  237
Thanksgiving is out of town and far away--I hav...     32    38   70
Thanksgiving is out of town but not too far--it...     49   126  175
All                                                   297   532  829

## Lien entre passer Thanksgiving entre amis avec l'âge et le revenu

- Générer un pivot de table pour regarder la moyenne d'âge des sondés pour chaque catégorie des questions 'Have you ever tried to meet up with hometown friends on Thanksgiving night?' et 'Have you ever attended a "Friendsgiving?"'.
> _Indications :_ utiliser les colonnes 'Have you ever tried to meet up with hometown friends on Thanksgiving night?','Have you ever attended a "Friendsgiving?"' et 'age_num'
- Faire de même pour les revenus avec ces 2 questions.

In [15]:
data.pivot_table(index='Have you ever tried to meet up with hometown friends on Thanksgiving night?',
                 columns='Have you ever attended a "Friendsgiving?"',
                 values='age_num')

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  46.731388  42.042105
Yes                                                 46.357923  39.578488